### ISSUE TITLE
Tests to prove specification is respected

### ISSUE THREAD

**Issue by kurko** [kurko/ember-json-api#41]
This is a list of things we need to test to make sure the adapter abides to JSONAPI.org.

- [x] Individual Resource Representations #30 
- [x] Resource Collection Representations #30
- [ ] Resource Types
- [ ] ~~Resource URLs~~
- [x] To-One Relationships #30
- [x] To-Many Relationships #30
- [ ] ~~URL Templates~~
- [x] Compound Documents #30
- [x] URLs for Resource Collections #30
- [x] URLs for Individual Resources #30
- [ ] ~~Relationship URLs~~
- [x] Creating an Individual Resource #30
- [ ] ~~Creating Multiple Resources~~
- [x] Updating an Individual Resource #30
- [ ] ~~Updating Multiple Resources~~
- [ ] Updating Attributes
- [ ] Updating To-One Relationships
- [ ] Updating To-Many Relationships
- [ ] Deleting To-One Relationships
- [ ] Deleting To-Many Relationships
- [ ] Deleting Resources
- [ ] Errors

~~Strikethrough~~ text is not planned.

**Comment by jonkoops** [comment]
I am closing this issue due to lack of activity and the impending deprecation in favour of the official Ember Data adapter.

**Comment by kurko** [comment]
:heart:
