### ISSUE TITLE
[Meta Issue] Deprecating in favour of official Ember Data adapter

### ISSUE THREAD

**Issue by jonkoops** [kurko/ember-json-api#86]
The Ember Data team has decided to support JSON API out of the box in the upcoming v1.0 release. Given these developments we have decided to deprecate this library and move our users to the official Ember Data solution.

This issue is to keep track of other issues related to this topic. But should also serve as a place to discuss what we can do to make the migration as smooth as possible.

- [x] Reach JSON API 1.0 compliance (see #82 and eneuhauser#14)
- [x] ~~Extend DS.JSONAPIAdapter and DS.JSONAPISerializer~~
- [x] ~~Remove any code from adapter and serializer that is duped in the Ember Data one~~
- [x] Add a deprecation notice to the README with a link to the official Ember docs
- [ ] ~~Add a deprecation notice to the Bower package~~
- [x] Add a deprecation notice to the NPM package

**Comment by wecc** [comment]
I've written down some steps that I think should be sufficient to transition to the new built-in JSON-API adapter/serializer:

1. Make sure that your API conforms to JSON-API 1.0

2. The built-in `JSONAPISerializer` expects `type` to be **plural dasherized** and `attributes/relationships` members **dasherized**

  If your API uses other conventions make sure to override `modelNameFromPayloadKey`/`payloadKeyFromModelName` and/or `keyForAttribute`/`keyForRelationship` to reflect your API

3. Update your adapter(s) and serializer(s) to extend from `DS.JSONAPIAdapter`/`DS.JSONAPISerializer`

4. Follow the transition guide to the new Serializer API if you have any customizations in your serializer (link to guide is on it's way).

Please let me know if there's anything else I can do to help. I'm also available on Slack during most of the day, CET.

**Comment by kurko** [comment]
This is awesome! Thanks @wecc for your hard work.

**Comment by Gayathri-r06** [comment]
Can you please confirm if the EmberJSONAPI serializer and adapter is working as expected? Can someone post a sample Ember model and API JSON?

Thanks much

**Comment by jonkoops** [comment]
@wecc Thanks for the feedback.

**Comment by jonkoops** [comment]
JSON API v1.0 compliance has been added in https://github.com/kurko/ember-json-api/issues/82.

**Comment by jonkoops** [comment]
I'm thinking maybe we should just go ahead and deprecate the library. I really want to move the code over to the latest Ember Data in the 1.13.x releases, but I just haven't had the time. @kurko would this be agreeable to you as well?

**Comment by kurko** [comment]
Yes. I also don't think it's worth our time and effort to move in parallel with ED.

**Comment by jonkoops** [comment]
This issue is closed by #89, we are now officially deprecated!
